### ISSUE TITLE
Authors link on blog homepage

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#107]
[ ]  The authors link would be either a link that the user would click to get to a page of all the authors and then could click a particular one from there, or a drop-down with the authors names. Clicking on an author name would return the existing author page.

**Comment by ethanbutler** [comment]
@KimPatch – I added an implementation of this to the staging site, under the Dialogue dropdown. The page will display any author with a published post or interactive.

**Comment by KimPatch** [comment]
@ethanbutler 
This has to be a link or drop-down on the blog page, not the menu. Can you do a drop-down in the sticky header that contains all the authors names, and you would click on an author's name to get to the authors page? (similar implementation as the contents drop-down). If that's not possible, then just a link to the authors page from the header. 
Also right now when I click one of the authors links it just takes me back to the site homepage rather than to the blog authors page.

**Comment by ethanbutler** [comment]
@KimPatch – I added a dropdown to the blog homepage. I also fixed the redirection issue you were describing, which was actually the result of a Yoast SEO setting that disabled author archive pages.

**Comment by KimPatch** [comment]
@ethanbutler 
Great – I like the implementation, and nice touch putting all authors at the bottom. 
A few details:
- [ ] Change the drop-down text Authors to "Blog Authors"
![image](https://user-images.githubusercontent.com/7329361/39252686-31b44f9c-4874-11e8-8840-b5bd087fa865.png)
- [ ] Add "posts" to the author boxes so they say “<name of author> posts”
![image](https://user-images.githubusercontent.com/7329361/39253241-6da89502-4875-11e8-9264-41b0701e314e.png)

- [ ] If possible, the shade of the drop-down text box should be the same as the searchbox above it before it's dropped-down (it's good if it's brighter when it's dropped down.)
- [ ] The background color of the drop-down should be the same blue as the field so the white text shows up well.
- [ ] The Author''s box isn't quite lined up with the search box above it – it's slightly off in Chrome and more off in Firefox. The left and right edges should line up, and they should be the same height if possible.
![image](https://user-images.githubusercontent.com/7329361/39252650-1afb9b34-4874-11e8-9f1e-04f344c67c02.png)

**Comment by KimPatch** [comment]
@ethanbutler The first two look good and the boxes are lined up now – thanks. But I'm still seeing the background color of the drop down as light gray in Firefox and white in Chrome, which means the author names don't show up very well. The background should be the same blue as the Drop-down box.

**Comment by KimPatch** [comment]
@ethanbutler the second and third checkboxes look good – thanks

We miscommunicated a bit on adding "posts". It should be on the gray boxes on the Authors page
![image](https://user-images.githubusercontent.com/7329361/39662314-9cd1cb54-502d-11e8-89ba-cc9ab7307f3a.png)
rather than the drop-down. Also, the word "posts" should not be capitalized.

**Comment by ethanbutler** [comment]
@KimPatch – this should be resolved.

**Comment by KimPatch** [comment]
Looks good – thanks!
