### ISSUE TITLE
Indent in Table of Contents

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#167]
**Current Behavior**: Both types of chapter headings are indented the same way table of contents drop-down._

**Desired Behavior**: If the two types of chapter headings are both present  NOTE chapter should indent in table of contents drop-down._

**Other details:** See Contents Test on the staging site for an example file with nested chapters.
If I'm remembering correctly, when we first added NOTE chapter these did nest.

The table contents should also nest according to <h tag
Here's another example:  http://rlhdemo.sanford.duke.edu/interactives/insite-guide-recording-transcribing-publishing-interviews/

And the drop-down box should also expand if there's room on the screen rather than requiring more scrolling.

**Comment by ethanbutler** [comment]
@KimPatch – this was not previously-discussed functionality, so this is an enhancement, not a bug. I'll have time to implement this next month.

**Comment by KimPatch** [comment]
@ethanbutler – great, sounds good

**Comment by ethanbutler** [comment]
@KimPatch - I pushed a change so that headings indent.

Your last concern – about users needing to scroll – depends on the browser UI, so there's not really anything we can do there.

Also, I would **really** strongly advise against using heading markup within a transcript file. The site is already set to generate the proper HTML for transcript based on the heading options established, so there is absolutely no need to do this. Doing so **will** generate non-semantic HTML, which is bad for accessibility. We can discuss this on our call next week if need be.

**Comment by KimPatch** [comment]
@ethanbutler The headings still don't indent in the table of contents drop-down. I added two tests to the staging site:

This is a simple test using the two types of headings
![image](https://user-images.githubusercontent.com/7329361/45459252-6be85180-b6c5-11e8-8d91-d5f964035ef8.png)

This is a report from the site
![image](https://user-images.githubusercontent.com/7329361/45459075-ac939b00-b6c4-11e8-8f92-17b2b2f27d46.png)

I was expecting the table of content to indent with both of these but neither does.

**Question for you:** What type of control do you have over the size of the drop down box – is it possible to make it bigger? Is it inadvisable for some reason?
It looks like the bottom item is the same on both Firefox and Chrome
![image](https://user-images.githubusercontent.com/7329361/45460042-507f4580-b6c9-11e8-8862-7ab17653b35f.png)

**Comment by ethanbutler** [comment]
@KimPatch – to answer your questions:

1. Headings do not indent because the parser only recognizes plain text and is designed to parse WebVTT, not HTML. **It is not an HTML parser.** To the parser, text with HTML markup is identical to text without. I can walk through this when we talk with Katie next week.
2. The size of the text box is OS and browser dependent. We don't have control over this.

I'm marking this issue as closed.

**Comment by KimPatch** [comment]
@ethanbutler Understood. Please take a closer look at the headings simple test. There's no HTML here – the two tiers are the regular WebVTT chapter tag and then the Note chapter tag. 

```
Part 1: Journalism Cornerstone – and Roadblock
00:00:02.000 --> 00:00:03.000
Interviews are an essential building block of journalism.

00:00:03.000 --> 00:00:04.000
Journalists rely on interviews to discover stories, collect facts, verify claims, assemble accounts of events, reveal voices, draw portraits of people and places, and check power.

NOTE Chapter Subhead – this should be indented in the table of contents
```
