### ISSUE TITLE
Advanced search issues

### ISSUE THREAD

**Issue by ethanbutler** [DukeLivingHistory/RLH-Site-Code#49]
**Checklist:** 

- [x] Search result jump links don't work for non-media interviews
- [x] Search result jump links don't work for timelines
- [x] Search result jump links need a hover state
- [x] Implement for collection search
- [x] Add "Expand All" button

**Questions:**
- [x] Should we limit the number of hits displayed per search result? For instance, search for "Vietnam" or another common phrase.

***

* For bugs, please add the "Bug" label 
* For feature requests, please add the "Enhanchments" label
* For general questions, add the "Questions" label
* When changes are satisfactory, please add the "Accepted" label to mark that changes are ready to push to production

**Comment by KimPatch** [comment]
I see what you mean about searching for something like Vietnam. Can we do an "…" fold rather than limiting the number of hits displayed? 

One more checklist item:
- [ ] this isn't yet implemented for the Collections search bar.

**Comment by KimPatch** [comment]
Collection search looks good, but four issues: 
[ ] I'm seeing duplicate entries – try searching for voting in the closing the polls collection, and the Timeline and Jay Delancey show up twice (both Firefox and Chrome).
[ ] Unlike the main search box, when I click on the interview I don't get straight to the instance and the search term does not appear in the Interview search transcript, annotations and descriptions text box  (both Firefox and Chrome).
[ ] View More button is too hard to miss – can you add the upside down triangle character for View More ▼ and the triangle for View Less ▲? 
[ ] I see where you're going highlighting the first entry when you click view more, but it stays highlighted when you move the cursor, which is confusing and distracting. Can this just be a plain highlight that moves when you move the cursor? Is it possible to put a subtle gray horizontal line before the first expanded entry in addition or instead? Thoughts?

And one question:
How hard would it be to do an "expand all" button – I'm thinking a good location is top right across from the hits and files text

**Comment by ethanbutler** [comment]
@KimPatch – the highlight behavior was a keyboard accessibility thing, since otherwise keyboard users would have to tab all the way back up to get to the "next" item. I've smoothed this out a bit so that if you mouseover another item, it removes the focus state *and* changing the focus state to grey instead of yellow so it's a bit more obvious what each indicates.

**Comment by KimPatch** [comment]
The highlight behavior looks great now.

View More/Less arrow looks great but there's one small issue with it: 
If you click "View More" then click "View Last" the arrow disappears.

**Comment by ethanbutler** [comment]
@KimPatch – I've pushed a fix for that, as well as the "Expand more" button. I've marked this as pending acceptance.

**Comment by KimPatch** [comment]
Thanks. The persistent arrow is great. The Expand All button is great as well.

One behavior issue: when I click expand, the focus stays the same, which is good. 
But when I click contract the focus jumps to the bottom of the file. 

What I expect to happen is the focus to stay the same from the viewer's point of view. So when the View More control changes to View Less, the new control should appear in the same position as the old control and everything that appears below the control row should remain in the same position to the viewer. So to the viewer the only thing that shows movement is the file that's contracting

**Comment by KimPatch** [comment]
I'm still seeing the focus issue. To test, search on "Vietnam",  then click the first interview View More, and it expands. There are lots of hits so you have to Scroll down to click View Less. Do so and it switches to the view less view, but you don't notice this because you are jumped to the very bottom of the file – user completely loses orientation. Here's another clue – this doesn't happen if there are just a few hits and no scrolling involved. So it acts differently when there are a lot of hits. I think the most extinct way to describe what should happen is this: whenever the user clicks the View More or View Less button, some part of the screen should remain stable to preserve orientation.

**Comment by ethanbutler** [comment]
@KimPatch – Thanks for bringing that up, that's a very good concern. I pushed a change that addresses this by moving the toggle above the hits. This makes it so that that the position of the toggle doesn't change upon selection, and it more closely mirrors the UI at the top of the page. It also eliminates the need for the focus logic, since there's nothing introduced to the source order that changes upon selection. Let me know if this works for you.

**Comment by KimPatch** [comment]
The toggle above the hits is a good solution, but there's one glitch – right now it always appears whether or not there is something to expand, which is confusing.

**Comment by ethanbutler** [comment]
Good catch – should be fixed!

**Comment by KimPatch** [comment]
Great – looks good!
