### ISSUE TITLE
Search doesn't work for Timelines

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#59]
**Current Behavior**: _Search doesn’t work for Timelines._

**Desired Behavior**: _Timelines should be included in main search._

**Other details:**
Test: 
- search for “Surrender” which occurs In both headings and text in the Civil Rights timeline.
- Search for “Henry Fry”  which occurs in supporting content in the Civil Rights timeline

**Comment by KimPatch** [comment]
This now appears in the search results, but when I click to the timeline I don't go straight to the hit I clicked, and the hits aren't highlighted.

**Comment by ethanbutler** [comment]
@KimPatch – I just pushed a fix that should address this.

**Comment by KimPatch** [comment]
I now see the terms highlighted in the text of a Timeline, but items in supporting content are still not highlighted. Search on Henry Fry or student to see this.
